{{- if .Values.ingress.enabled }}
# This is a trash hack to generate tls
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "..fullname" . }}"
  labels:
    {{ include "..labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  tls:
    - hosts:
      {{ range .Values.ingress.hosts }}
        - {{ . }}
      {{- end }}
      secretName: ldap-tls
  rules:
    {{ range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ include "..fullname" $ }}"
                port:
                  name: ldaps
    {{- end}}
{{- end}}
